### ISSUE TITLE
Possible to make corpus available?

### ISSUE THREAD

**Issue by messersc** [saezlab/progeny#28]
Hi,

this is such a nice project and well put together. I was wondering if it would be possible to make publicly available the corpus on which progeny is trained, as it would greatly benefit others when training new models or comparing performance with different training sets per pathway.

Thank you,
Clemens

**Comment by alberto-valdeolivas** [comment]
Hi @messersc,

Many thanks for your interest in the project. 

You can find the information about the corpus of the datasets used in the Supplementary note 1 from the [progeny publication] (https://www.nature.com/articles/s41467-017-02391-6) for the 11 original pathways. Then, we added 3 more pathways for which you can find the details in the supplementary table 1 of this [publication](https://www.sciencedirect.com/science/article/pii/S1874939919302287?via%3Dihub). 

Best regards,
Alberto.

**Comment by messersc** [comment]
Hi Alberto,
thanks so much for getting back to me! I was thinking about the intermediate and/or final data frames that are used to train the model. That would be much easier than download all experiments from GEO again, but I understand if this is not easily possible.

Kind regards,
Clemens

**Comment by alberto-valdeolivas** [comment]
Hello Clemens, 

Yeah, I understand your point. 

@mschubert @bence-szalai do you know if this information is available somewhere? 

Best regards,
Alberto.

**Comment by mschubert** [comment]
Hi @messersc!

I updated the [footprints repository release](https://github.com/saezlab/footprints/releases/tag/publication) to include the z-scores computed from the microarrays, which I think is what you want.

As a "corpus" itself, I'd recommend the [collection of yaml files](https://github.com/saezlab/footprints/tree/master/index) instead of Supplementary note 1.

@bence-szalai is working on putting the additional pathways on Zenodo as well.
